### ISSUE TITLE
Request: helping a brother out

### ISSUE THREAD

**Issue by DonaldTsang** [franciscapessanha/Hand-pose-recognition#1]
See https://www.youtube.com/watch?v=DQ8orIurGxw
The Original author of https://github.com/carykh/jumpcutter did not integrate the solution of thumbs up and thumbs down, hope that you can improve his software and make it happen.
Thanks

**Comment by franciscapessanha** [comment]
This project a University project and won't be developed any further.

**Comment by DonaldTsang** [comment]
@franciscapessanha this is more of a request for collaboration than anything else.
If you are free maybe you can give guidance to the developer.
